---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlclusters.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLCluster
    singular: mysqlcluster
    plural: mysqlclusters
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackups.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLBackup
    singular: mysqlbackup
    plural: mysqlbackups
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlrestores.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLRestore
    singular: mysqlrestore
    plural: mysqlrestores
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackupschedules.mysql.oracle.com
spec:
  group: mysql.oracle.com
  version: v1
  scope: Namespaced
  names:
    kind: MySQLBackupSchedule
    singular: mysqlbackupschedule
    plural: mysqlbackupschedules
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: mysql-operator
      containers:
      - name: mysql-operator-controller
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: wcr.io/oracle/mysql-operator:{{ .Values.image.tag }}
        ports:
        - containerPort: 10254
        args:
          - --v=4
{{- if not .Values.operator.global }}
          - --namespace={{- .Values.operator.namespace }}
{{- end }}    